[connections.gsheets]

spreadsheet = "https://docs.google.com/spreadsheets/d/1OefaGTNypH1nj5FcsEdAMz16iEFhFyrYLyOxv3gr_Mk"

type = "service_account"

project_id = "projectbigquery-474916"

private_key_id = "3fbbedcb8e158fa987718c9d311498503b2876c8"

private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDIRHWCpnUf7VlW
qrxxHuzdNrHIBszCv0uuFR3Yt2XdAJE0IyGSpjEmVJIoevjGOQdkOBlqoUM2EGc+
mGo5DduUDzTCy3MgNaaMxuKaLyx5YQewLO2DLyT95eE/ModKmeWGLy1lL/4FiwcA
wG1OE2/um4d97SYU4zo3X8uOk4DF9E9iL09xZAjpbHcdc6yHXOO1WiBmD6GVOoyy
1B1JJqTP2M/974GFXEnFOqXxzUetDFlUuS1sR3bg2Yg51qndXqWdxFaIHleaDUlA
bRHPsHzVJffCe9cNZ1lZdfA1k0RbKptT65xImW4AQq5+4BE+RtA/26Po0owZ4KyQ
Fk62rcH5AgMBAAECggEAFOOvLjWWugHT88pTZalII7r0yFyNNzMk/b+OIXDf2zGX
88xGUDmtnsXriPVqxaJlNvrzC8BOdnE3k7vqOJFNeiAr7LW0CIQQH1cPg+2vwelx
F9tX2vsr7J/x4tmuawWqf1ikb42V/ZYG4PkxbZdxcX4fn+8AreUVyXjgjrqsD/nA
nKHLDsuG9Xj+Vv7ZUWem5JiG085I3AIvlrQxQw5SJJwoSR1vG8ztfVPfPmxFxr1k
vPAdtLQUh32UMiJZ+UKBhMeweZ16fqVYBIMBGvWArYfN0NXqqCOmCiL7w5z5p0BM
kxfDfoUTSgDrPu3x9VmIdlEbktS+jlgMWWh4t8Q0QQKBgQDo8fthor8nOC6mgUKz
iNGfOztbsZTpaDBxcCDVZuICxMlhBZgmV6Ap9uK2MLWV9MLxHCBxBTL2Q8krfJbE
pPk4c5s1SR928AI5pGSTcN839OXXcYNP0aakpO7+LaW0E5KgvvuWJktxbJgoEhqL
/KFqCCZ4nVLmeEBDqcw4ocYTXQKBgQDcFokGM6i16ipZOUgt3M3D8YdY1wpZHrHk
ZvV91pmFn0V524Qi9Y9v3Kw/9WOiB0KJPQ75o2FzcpfJ82FLsdy1iuIUdvIkEUIV
+zCUBGSuXjXQme5cdvw+JnujvZoUilRHJmBGAtOJRN21UQPNVZaAb/jORj5vI9nU
jDtTo3m7TQKBgQDILyvYvAOJsL5mWK75mpqKPFzGb9WIwADhe3q76a5QssxclHIs
gSEi7wflifaC59SfX4yBk/Y3rAk1Vdw7IYsK+E5pfG2NyLQg1SWZj2ZEsDDU9Lfj
4EdVNmgsBw5fsnJPsdCDOGWdE7WuueAWbQRKGrb08D5N0QlpHIJkKKIQAQKBgHbA
DgTzoKcvBtSHjMN6LOf5jR7JQIMfhbqINxND1Cf97P24DM7UEiW4OpRz8eM96Y+l
C0x09CLXhMDpeejeugiWPC/wkewWB8NWejqTOEPA/2Zjd/IaHTXni7Som9dTX+/X
7AA6jCq3pqyrXtLOyFraj7O0wQE0pdcCJwyU2xzNAoGBAK1Baa/XdlsxApR6U/0G
nd5VlJCsHvVg6xoi3K3WN1hz6XIg5ybHN6AK2Am2FqgycQJU+SyrV4h1uFw5DoZNO
moWOKux98ylsEOTtCpSll9NPPSFhxdoMs1r8r+6vD2zcv5RdNE6vGoK8hprNXOCR
C0gHEz6+8d/f0g0++vRisyRF
-----END PRIVATE KEY-----"""

client_email = "controlfinanciero@projectbigquery-474916.iam.gserviceaccount.com"

client_id = "118276688378182381415"

auth_uri = "https://accounts.google.com/o/oauth2/auth"

token_uri = "https://oauth2.googleapis.com/token"

auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"

client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/controlfinanciero%40projectbigquery-474916.iam.gserviceaccount.com"

universe_domain = "googleapis.com"